# Generated by Django 5.2.1 on 2025-05-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalqa_title_alter_document_title'),
    ]

    operations = [
    ]
